"""Detection pipeline for Provenance Guard.

Two independent signals, each returning P(AI) in [0, 1]:
  - llm_signal:        semantic coherence, via Groq (llama-3.3-70b-versatile).
  - stylometry_signal: structural uniformity, pure Python.

combine_signals() fuses them into a calibrated verdict + confidence.
"""

import json
import os
import re

# Weights and thresholds (mirrors planning.md section 2). Changing these here is
# the single source of truth for calibration.
LLM_WEIGHT = 0.65
STYLE_WEIGHT = 0.35

AI_THRESHOLD = 0.70  # combined_p >= this -> likely_ai (deliberately high)
HUMAN_THRESHOLD = 0.35  # combined_p <= this -> likely_human
HIGH_CONFIDENCE = 0.80  # confidence >= this -> "high confidence" wording

GROQ_MODEL = "llama-3.3-70b-versatile"

LLM_PROMPT = (
    "You are an AI-content detector for a creative writing platform. Read the text "
    "below and judge whether it was written by a human or generated by an AI system. "
    "Consider semantic coherence, rhetorical structure, hedging, uniformity, and the "
    "overall 'flavor' of the prose. Respond with ONLY a JSON object of the form "
    '{{"ai_probability": <float 0..1>, "rationale": "<one short sentence>"}} where '
    "ai_probability is your probability that the text is AI-generated (1.0 = certainly "
    "AI, 0.0 = certainly human). Do not include any text outside the JSON.\n\n"
    "TEXT:\n{text}"
)


def _clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))


# --------------------------------------------------------------------------- #
# Signal 1: Groq LLM (semantic)
# --------------------------------------------------------------------------- #
def llm_signal(text: str):
    """Return P(AI) in [0,1] from the Groq LLM, or None if Groq is unavailable.

    None signals a degraded run so the caller can fall back to stylometry alone
    and cap confidence accordingly.
    """
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return None
    try:
        from groq import Groq

        client = Groq(api_key=api_key)
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": LLM_PROMPT.format(text=text)}],
            temperature=0.0,
            response_format={"type": "json_object"},
        )
        content = resp.choices[0].message.content
        data = json.loads(content)
        prob = float(data.get("ai_probability"))
        return _clamp(prob)
    except Exception:
        # Network error, bad key, malformed JSON, etc. -> degrade gracefully.
        return None


# --------------------------------------------------------------------------- #
# Signal 2: Stylometry (structural)
# --------------------------------------------------------------------------- #
def _split_sentences(text: str):
    parts = re.split(r"[.!?]+", text)
    return [p.strip() for p in parts if p.strip()]


def _words(text: str):
    return re.findall(r"\b\w+\b", text.lower())


def stylometry_signal(text: str) -> dict:
    """Return structural AI-likeness as P(AI), plus the sub-metrics for transparency.

    Three sub-scores (each an AI-likeness in [0,1]) are combined:
      - burstiness (sentence-length variance) -- weighted highest
      - vocabulary diversity (type-token ratio)
      - punctuation variety
    """
    sentences = _split_sentences(text)
    words = _words(text)
    num_words = len(words)

    # --- Burstiness: AI text is metronomic (low coefficient of variation). ---
    lengths = [len(_words(s)) for s in sentences]
    if len(lengths) >= 3 and sum(lengths) > 0:
        mean_len = sum(lengths) / len(lengths)
        variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
        std = variance ** 0.5
        cv = std / mean_len if mean_len else 0.0
        # cv >= 0.6 reads very human; cv == 0 reads very AI.
        ai_burstiness = 1.0 - _clamp(cv / 0.6)
    else:
        # Too few sentences for variance to mean anything -> neutral.
        ai_burstiness = 0.5

    # --- Type-token ratio: very repetitive vocab leans AI-like. ---
    if num_words > 0:
        ttr = len(set(words)) / num_words
        # ttr <= 0.3 -> AI-likeness 1.0; ttr >= 0.8 -> 0.0.
        ai_ttr = 1.0 - _clamp((ttr - 0.3) / 0.5)
    else:
        ai_ttr = 0.5

    # --- Punctuation variety: humans use more diverse punctuation. ---
    expressive = set(re.findall(r"[!?;:\-\u2014\u2013()'\"\u2026]", text))
    distinct = len(expressive)
    # 0 distinct expressive marks -> AI-likeness 1.0; >=4 -> 0.0.
    ai_punct = 1.0 - _clamp(distinct / 4.0)

    style_p = _clamp(0.55 * ai_burstiness + 0.20 * ai_ttr + 0.25 * ai_punct)

    return {
        "style_p": round(style_p, 4),
        "metrics": {
            "ai_burstiness": round(ai_burstiness, 4),
            "ai_ttr": round(ai_ttr, 4),
            "ai_punct": round(ai_punct, 4),
            "num_sentences": len(sentences),
            "num_words": num_words,
        },
    }


# --------------------------------------------------------------------------- #
# Fusion + calibrated scoring
# --------------------------------------------------------------------------- #
def _attribution_and_confidence(combined_p: float):
    if combined_p >= AI_THRESHOLD:
        return "likely_ai", combined_p
    if combined_p <= HUMAN_THRESHOLD:
        return "likely_human", 1.0 - combined_p
    # Uncertain band: confidence reports how *unsure* we are (peaks at p == 0.5).
    return "uncertain", 1.0 - 2.0 * abs(combined_p - 0.5)


def combine_signals(llm_p, style_p: float) -> dict:
    """Fuse the two signals into a verdict + calibrated confidence.

    If llm_p is None (Groq unavailable) we fall back to stylometry alone and cap
    confidence so a single structural signal can never yield a *high-confidence*
    verdict.
    """
    if llm_p is None:
        combined_p = style_p
        signals_used = ["stylometry"]
        degraded = True
    else:
        combined_p = LLM_WEIGHT * llm_p + STYLE_WEIGHT * style_p
        signals_used = ["llm", "stylometry"]
        degraded = False

    combined_p = _clamp(combined_p)
    attribution, confidence = _attribution_and_confidence(combined_p)

    if degraded:
        confidence = min(confidence, 0.75)  # never "high confidence" on one signal

    return {
        "attribution": attribution,
        "confidence": round(confidence, 4),
        "combined_p": round(combined_p, 4),
        "llm_score": round(llm_p, 4) if llm_p is not None else None,
        "style_score": round(style_p, 4),
        "signals_used": signals_used,
        "high_confidence": confidence >= HIGH_CONFIDENCE,
    }


def classify(text: str) -> dict:
    """Run the full pipeline on `text` and return the combined decision dict."""
    llm_p = llm_signal(text)
    style = stylometry_signal(text)
    result = combine_signals(llm_p, style["style_p"])
    result["style_metrics"] = style["metrics"]
    return result
